### ISSUE TITLE
Hangs with Cloud CP/M and Ishkur CP/M

### ISSUE THREAD

**Issue by snhirsch** [masto/nabu.run#13]
Hi, not sure if this expected at the current state of development, but copying files from one logical disk to another fails under both flavors of CP/M.  Cloud CP/M wants a 'replace' API operation that's not implemented and Ishkur CP/M just hangs.  I find Cloud CP/M troublesome even on the author's adapter, but Ishkur shows no issues with, e.g. nns or the opensource internet adapter.

**Comment by masto** [comment]
Hi,

nabu.run currently doesn't have any local file support, so there would be no place to copy files to. The other adapters run on your computer and can access your hard drive to store their virtual disks.

Issue #10 is the tracking bug for adding support to access your local disk from a web page. I do intend to find a solution here, but the APIs for this have limited functionality for security reasons.
